### PR TITLE
Improved link directive.

### PR DESCRIPTION
**Pull request by omerman**
* Support element update.
* Support activation/deactivation of the directive.

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
Thank you for submitting this PR!

Could you please give me some more context on what the fixes or improvements are?

**Comment by omerman** [comment]
@ItalyPaleAle Basically you can now shut off the link directive, added an "active" prop.
Also I noticed that there were some bugs when the component updates, so I took care of it as well.

I'll take a look in the tests soon.. see if I can fix them.
Not sure how to generate the function comments... Could you help me with that?

**Comment by ItalyPaleAle** [comment]
Could you gie me an example of how this works? Of what new APIs are introduced? I might be able to help with tests.

One more thing... The formatting of the file changed (I guess your editor is running a formatter automatically on saving which is configured differently from the style of this repo). can you please run eslint with `--fix` to ensure that the formatting is consistent with the rest of the repo? (e.g. no semicolons, etc)

**Comment by omerman** [comment]
I had a use case where I rendered a markup within an `{#each}` template, and I wanted some links to be disabled in some cases.. and the list can also be sorted, so when it did, the update method of the directive was fired, and a lot of errors popped up, so I fixed everything and added the ability to opt out of using the markup as a link.
I'm not sure if it is the best idea, what are you thoughts?
 
It looks something like this:
```
<a use:link={{active: shouldLinkBeActive}} href="/path/to/somewhere" />

<a use:link={{active: shouldLinkBeActive, href: '/another/variant'}} />
```

**Comment by ItalyPaleAle** [comment]
Oh this is a good idea!! I understand now and I think it makes sense.

As for naming, I'm concerned with the fact that `active` could be confused with the `use:active` action. How about renaming it to `disabled`? (or `enabled`, although for a flag that turns something off, I'd prefer the negative one)

**Comment by omerman** [comment]
Ah I forgot about the "use:active". Sure I'll change it. I'm also think about making it backward compatible, meaning supporting passing href alone, Now it doesn't support this variant any longer, and it's kind of the main use case..

**Comment by ItalyPaleAle** [comment]
Yes please, backwards-compatibility is very important for this project whenever possible!

**Comment by omerman** [comment]
@ItalyPaleAle I fixed the lint issues. I squashed it to one commit.
Everything seems to be working. 

Could you take care of the tests? I couldnt run them for some reason..
And also there is some methods generated code that Im not sure how to generate, could you help me with that as well?

**Comment by ItalyPaleAle** [comment]
Thanks again for suggesting this feature.

I have refactored the PR so it disables links by just doing `event.preventDefault()` on the click handler, which avoids changing the value of `href` when the link is disabled (also because `void:0` is not good for a11y).

Will merge.

**Pull request merged**
