### PR TITLE
Enable HTML code highlighting for .svelte files

### PR DESCRIPTION
**Pull request by sisou**
Code highlighting for `.svelte` files is currently waiting to be merged (https://github.com/github/linguist/pull/4504).

Until then we can force HTML code highlighting according to https://github.com/sveltejs/svelte/issues/2567.

For the attribute to take effect, `.svelte` files need to be changed so that Linguist updates their meta data on Github's servers. That's mostly the reason for the changed `App.svelte` and `router.svelte` files. `App.svelte` and `main.js` also had their executable bit set, so double-clicking them asked me to execute them instead. This is also fixed in this PR.

### CODE REVIEW

**Comment by sisou** [comment]
You can see the highlighting in effect in my branch:
https://github.com/sisou/svelte-spa-router/blob/code-highlighting/router.svelte

**Comment by ItalyPaleAle** [comment]
This is great! Thanks for your contribution 👍 

I assume that once github/linguist#4504 is merged I should revert this, to use the highlighter for Svelte and not a generic HTML one. Correct?

**Comment by sisou** [comment]
Yes, I believe so.

**Comment by sisou** [comment]
https://github.com/github/linguist/pull/4504 was merged 9 days ago, so _I think_ it's now safe to remove the `.gitattributes` file again.

**Pull request merged**
