### PR TITLE
feat: svelte 4

### PR DESCRIPTION
**Pull request by mikeychowy**
upgrade svelte version to 4, I've used the migration script and manually trying to find what else needs to be changed, built the test app and nothing seems broken.

can't for the life of me figure out how to run the nightwatch test

### CODE REVIEW

**Comment by mikeychowy** [comment]
@ItalyPaleAle

**Comment by ItalyPaleAle** [comment]
@mikeychowy thanks a lot for this PR!

You must have your editor configured to run the linter automatically on save. Because of that, pretty much every line of the source code was modified by the linter, and reviewing the PR and understanding what the real code changes are is almost impossible :(

Can you please do either one of:

1. Please un-do the changes that are due to the linter only and keep this PR only for the changes related to Svelte 4 support
1. OR Open a separate PR to set up a linter in this repo and lint the code (without making any other code changes)  - however, please make sure that coding conventions currently in use (such as no semicolons) are respected. Then we can rebase the PR on top.

**Comment by mikeychowy** [comment]
I made changes to linter as well since `eslint-plugin-svelte3` was deprecated in favor of `eslint-plugin-svelte` in svelte 4, but you're correct,  it does make any changes to code base impossible to understand, let me reopen this PR later with just the svelte 4 changes

**Comment by pcfreak30** [comment]
Just came across this @mikeychowy and would really appreciate that new PR. May just have to apply this diff anyways, but I definitely need this for my current project.

Kudos.

**Pull request closed without merging**
