### PR TITLE
Update active.js

### PR DESCRIPTION
**Pull request by TorstenDittmann**
splice returns the deleted item and overrides the nodes. See #28

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
Thanks a lot for catching this bug and submitting a PR! Any chance you could add a test case for this too, so we'll avoid a regression in the future?

**Comment by TorstenDittmann** [comment]
No Problem :) 

Of course I can do that, I've never really done testing in JS before, but that would be an opportunity. Should I just add a test to https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/test/02-active-action.test.js ?

**Comment by ItalyPaleAle** [comment]
Yes, please, if you don't mind! That file contains the actual tests (ie. tells the "fake browser" what to do). You might also need to add a loop with links in the sample code: https://github.com/ItalyPaleAle/svelte-spa-router/tree/master/example (This is probably very similar to what you've written in #28 to demonstrate the issue)

**Comment by TorstenDittmann** [comment]
Closing this. Look here #30

**Pull request closed without merging**
